# Generated by Django 4.2.5 on 2023-09-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_price_item_product_stock_alter_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_stock',
        ),
    ]
